{
 "title": "AvitoShop dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Количество запросов в секунду (RPS)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 13, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(shop_space_http_shop_app_requests_total[5s])"
    },
    {
     "expr": "sum(rate(shop_space_http_shop_app_requests_total[5s]))"
    }
   ]
  },
  {
   "title": "SLI Latency (Время ответа, Percentile Latency)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 13, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99,\nsum(rate(shop_space_http_shop_app_response_time_seconds_bucket[5s])) by (le, status)\n)"
    }
   ]
  },
  {
   "title": "SLI Успешности ответов (Success Rate, Availability)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 13, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum(shop_space_http_shop_app_successful_responses_total) \n/\n(\n  sum(shop_space_http_shop_app_successful_responses_total) \n  + \n  sum(shop_space_http_shop_app_failed_responses_total)\n) \n* 100\n",
     "legendFormat": "Процент успешных ответов"
    }
   ]
  }
 ]
}