services:
  # Сервис для приложения
  app:
    container_name: AvitoShop
    build:
      context: . 
      dockerfile: Dockerfile
    ports:
      - "${HTTP_PORT}:${HTTP_PORT}" 
      - "${SWAGGER_PORT}:${SWAGGER_PORT}" 
    depends_on:
      db:
        condition: service_healthy
    restart: always

  # Сервис для PostgreSQL
  db:
    container_name: postgres
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DB}
    ports:
      - "${DB_PORT}:${DB_PORT_INTERNAL}" 
    volumes:
      - postgres_volume_local:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U postgres -d shop'"]
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 10s

  # Сервис для миграций
  migrate:
    container_name: migrator
    build:
      context: . 
      dockerfile: migration.Dockerfile
    restart: on-failure
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
    env_file:
      - .env 

  # Сервис для тестирования
  DB_Test:
    container_name: test_DB
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: avito_test
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
    ports:
      - "5433:5432"
      
volumes:
  postgres_volume_local:
